### ISSUE TITLE
transferring coins from stratis Staking wallet to Electrum

### ISSUE THREAD

**Issue by steelliberty** [stratisproject/electrum#10]
Hello.  

I downloaded and installed the stratis staking wallet, however it will not connect to the network. In the mean time, thinking the wallet was up and running, I bought some Stratis coin using an address from that wallet.  

How can I export the private keys from the stratis wallet or what procedure can I use to obtain the coin from the wallet which will not function to the electrum wallet which does function ? 

thank you

**Comment by dev0tion** [comment]
You can use the dumpprivkey command: https://en.bitcoin.it/wiki/Original_Bitcoin_client/API_calls_list
