### ISSUE TITLE
error: TX rejected

### ISSUE THREAD

**Issue by marcel20000** [stratisproject/electrum#11]
Hello,

I want to send some stratis, and when i send i get this:
signing transaction (so this is ok)
broadcasting transaction (so this is also ok, but then)
error:TX rejected (i trying to send a couple off times and also starting up everything but still this error will come, i have more than i will send so the fee is also ok, so can somebody help me?
tnx

**Comment by dev0tion** [comment]
Hey @marcel20000, please try to set a manual transaction fee higher than 0.0001.

**Comment by marcel20000** [comment]
I did that allready (with and without the automatic fee-checkbox on) but it won't help.
i use the portable wallet version, so i switch to the install version but also this version can receive but can not send (same error).
I put the portable  version on my usbstick and try to send it on another (windows 10) laptop (in the same network) and it worked. jeeeeej.
So i think there is some kind of communication/firewall blocking on that laptop although i have no problems with other electrum programs.

I give this info, because mabye someone else find it usefull.
still im curious what it blocks, so if i have time left (hahaha) im gonna find it and let u know.

Thanks for your reaction dev0tion.
