### ISSUE TITLE
Cannot Create a Wallet Using Master Public Key

### ISSUE THREAD

**Issue by joelmlee** [stratisproject/electrum#12]
Hello-
I'm attempting to create a watch-only wallet with the electrum-stratis wallet (2.7.17). I have installed and generated keys on a cold storage partition. Then I am:
Exporting the master public key from my offline installation.
Installing a new Stratis wallet as a standard wallet on my online partition.
Choosing the option to provide a key.
Pasting in the master public key.
When I paste in the master public key, the 'Next' button stays greyed out, as if the key is not valid. I notice that for my Bitcoin installation, the master public key begins with "xpub," and so I have also tried adding that to the beginning of the string to no avail.

**Comment by dev0tion** [comment]
Fixed in #6, will be included in the next release.
