### ISSUE TITLE
Runaway error on Mac

### ISSUE THREAD

**Issue by robca888** [stratisproject/electrum#16]
I cannot launch electrum. I get this error.

Exception: St13runtime_error
CDB:Error -30974, can't open database
stratis in Runaway exception

How do I fix this?

**Comment by 986S** [comment]
I had the same problem.

It is my first instalation. I had no coins and I sent never Stratis from this Mac and this Wallet.

I try to delet and install again. I had the same error. 

ein fataler Fehler ist aufgetreten. Stratis kann nicht fortgesetzt werden und wird beendet.

Exeption: ST13runtime_error 
CBD : Error - 30974, can't open datebase stratis in runaway exeption.

What can I do?

I use a Imac with Os X EL Capitan Version 10.11.6 and Stratis-Qt-v2.0.0.3-osx.dmg

**Comment by dev0tion** [comment]
@986S and @robca888 please use v2.0.0.2 of our Qt wallet
