### ISSUE TITLE
New to Wallet: electrum-stratis-2.7.17-win-portable.zip 

### ISSUE THREAD

**Issue by AjainStrat** [stratisproject/electrum#17]
Installed the wallet. Sent some Stratis through Changelly.
Block Explorer shows Not yet redeemed.
Nothing in Wallet.
Wallet is always offline.
What should I do?

**Comment by dev0tion** [comment]
Hi,

Not yet redeemed is normal, it will only be redeemed once you send out the funds.
Keep the wallet open for a while, it will connect.
If not check your anti-virus and otherwise please contact me again.

Thanks

**Comment by WalterGrum** [comment]
Hi, 

I am new to electrum wallet.  I installed the wallet 6 days ago and checked with the anti-virus to allow.  Wallet still not completely synchronizing and doesn't stay connected.  I transferred Stratis through Changelly on the 26th and it is still saying not yet redeemed and nothing is showing in my wallet.   Not sure what to do, not extremely tech savy.

**Comment by AjainStrat** [comment]
Had to exit out of the wallet. Log in with the passphrase again. Got connected online automatically and received the STRATIS. It just takes a little while.
Thank you for your help.
