### ISSUE TITLE
Connecting to server

### ISSUE THREAD

**Issue by issa14000** [stratisproject/electrum#18]
Dear,

My stratis electrum is not connecting to server. The version I have is 2.7.17. I have a back up with two transactions, I loaded this text file. I can see these transactions and my balance. However they are not verified. I know my seed and password. Automatically connecting does not work, the ball is red all the time on the bottom right side. Left bottom side says not connected as well. What would be a solution that my balance would be verified?

Kind regards,

issa
![stratis-notconnected](https://user-images.githubusercontent.com/33362313/32400193-5eac1952-c0fd-11e7-8054-10b3ddce1166.jpg)

**Comment by OjhaPrashant** [comment]
I am also having the same issue.

**Comment by OjhaPrashant** [comment]
I have downloaded and installed 2.7.17 on windows 10. After opening it, on bottom left it shows "Not Connected" and bottom right corner have red color. Please help fixing this issue as I have transferred some coins to this wallet address

**Comment by dev0tion** [comment]
@ojha1730 it will connect after a while
