### ISSUE TITLE
Connect to Ledger Blue

### ISSUE THREAD

**Issue by sipsorcery** [stratisproject/electrum#19]
I've installed the Stratis App on my Ledger Blue but can't find how to connect the electrum-stratis wallet to it. Is it done as part of the electrum wallet intialisation? I kept an eye out when doing that but didn't see anything.

**Comment by orkrad** [comment]
I ran into the same issue. Electrum-stratis-2.7.17 does not appear to support the Ledger hardware wallets anymore. Does anyone have an update on when this will be fixed?
