### ISSUE TITLE
TX Rejected

### ISSUE THREAD

**Issue by hendrikvdt** [stratisproject/electrum#20]
Hello

I while ago I purchased some Stratis coins and send them to the Electrum Stratis wallet, unfortunatly when I try to send some back to another address I keep getting the TX rejected error, I tried several solutions which I foun online. Unfortunatly none of them worked. The version which I use is: 2.7.17.

I tried to raise the fee and changing some settings, none of this worked unfortunatly.
Could you please help me find the cause of this problem so I can send the coins to another address? Please let me know which information you need.

I keep getting the following error:
![electrum-stratis](https://user-images.githubusercontent.com/34351277/33733955-a7651ea2-db8b-11e7-9d85-5573fbb0bbdc.PNG)

Looking forward hearing from you.

**Comment by dev0tion** [comment]
Hi, the problem is probably that you're not syncing your system clock automatically.
Please try doing that and try sending again.

**Comment by hendrikvdt** [comment]
Thans dev0tion for your fast reply. 

Strangely enough this options was already set to autmatic syncing of the system clock. But after turning the setting off and back on it fixed the problem and I could succesfully send the coins to another wallet.

Thanks for your help.

**Comment by dev0tion** [comment]
Good to hear and you're welcome.

**Comment by Sytd3h5** [comment]
> Hi, the problem is probably that you're not syncing your system clock automatically.
> Please try doing that and try sending again.

How do I sync my system clock? I am using windows 10 by the way

**Comment by dev0tion** [comment]
@Sytd3h5 
- Right click time/date in the corner of your taskbar
- Select  "Adjust date/time"
- Toggle on "Set time automatically". If it was already on, toggle it off and on.

**Comment by Sytd3h5** [comment]
@dev0tion 

Thank you!
