### ISSUE TITLE
Cannot tranfer funds out of Electrum-stratis wallet.

### ISSUE THREAD

**Issue by stratboy11** [stratisproject/electrum#22]
Have been trying to transfer funds out of my stratis electrum wallet, failing each time.

Also this error pops up every time i try

error: TX rejected

Please Help.

p.s: Yes i am upgraded to the latest version v2.7.17.

**Comment by stratboy11** [comment]
Also this error pops up every time i try 
 
  error: TX rejected

**Comment by tylerblc** [comment]
I am having the same issue. I rebuilt the wallet from seed with the same result. No matter how high I set the fee the transaction is rejected (tried up to .1 strat)

**Comment by dev0tion** [comment]
@stratboy11 @hackinthebochs 
Try setting your system clock to automatic (if it's already on it, switch to manual and back to automatic).

**Comment by tylerblc** [comment]
That fixed it for me. System clock was off by about 10 minutes. Thanks!
