### ISSUE TITLE
Issue creating a watching-only wallet

### ISSUE THREAD

**Issue by dpancra** [stratisproject/electrum#23]
Hi all, I am trying to create a watching-only wallet but when I enter the Master Public Key from the offline installation into the online PC (in the "Create Keystore from Keys" screen) the button "next" stays grey and I cannot go ahead.
Steps:
1. selected "Standard Wallet"
2. "Use public or private keys"
3. Entered the Master Public Key
I have verified the key several times, copy/pasted (as usual) and even tried to type it, but nothing doing.
I have followed the same procedure for Electrum BTC and LTC and everything was ok.
Could someone please help?
Thanks!

**Comment by dev0tion** [comment]
Hi @dpancra, this will be fixed in the upcoming version.

Grts

**Comment by dev0tion** [comment]
Fixed in #6 
New binaries coming soon.
