### ISSUE TITLE
Error: Tx rejected

### ISSUE THREAD

**Issue by Rajka** [stratisproject/electrum#24]
Hi, i want to send startis to another wallet. it's showing error : Tx rejected. Could someone please show me how to fix this?
![image](https://user-images.githubusercontent.com/29011904/35189602-43fdc41a-fea2-11e7-8a70-8021bfa3cf22.png)

**Comment by dev0tion** [comment]
Check out the solution here: https://github.com/stratisproject/electrum-stratis/issues/20
