### ISSUE TITLE
error: TX rejected

### ISSUE THREAD

**Issue by Goodblue77** [stratisproject/electrum#27]
I've been having issues with the electrum wallet for some days now where I want to transfer my STRAT from the electrum wallet to my new qt wallet.

Around 2 days ago I transfered 0.1001 STRAT to my new wallet as a test transaction to be sure it was the right address. After that I wanted to transfer the rest of them to my new wallet and got an error message: error: TX rejected.

Re-installed the electrum wallet and did another test transfer. This time 4.92 STRAT and that was successful, however after this transfer I wanted to transfer the rest of my STRAT and got the same error message.

I used the "Max" button to get the maximum transferable amount. I also tried using a higher TX fee (the slidebar) but no luck there either.

**Comment by dev0tion** [comment]
Hi @Goodblue77,

This will solve your issue: https://github.com/stratisproject/electrum-stratis/issues/20

Cheers
