### ISSUE TITLE
Hi, I need help. I have strat in electrum stratis wallet which shows Not Connected. 

### ISSUE THREAD

**Issue by mississaugaguy** [stratisproject/electrum#34]
Hi, I need help. I have strat in electrum stratis wallet which shows Not Connected. I want to send them to my newly created strax wallet Can someone please help me out

**Comment by dev0tion** [comment]
Hi, please join the #support channel in our Discord server: https://discordapp.com/invite/9tDyfZs
They will gladly help you get sorted.
