### ISSUE TITLE
Won't start on Win7

### ISSUE THREAD

**Issue by EmilPD** [stratisproject/electrum#4]
When installed it won't start. Then i downloaded portable version and it works, but why the normal version does not want to start?

**Comment by dev0tion** [comment]
Hey @EmilPD,
Do you get some kind of error message when opening the installed client?

**Comment by EmilPD** [comment]
no - no error message, just it did not give any indication that it will start (for a minutes) and it was not registered as process (when looking with task manager).

**Comment by dev0tion** [comment]
@EmilPD ok, I am not able to reproduce this bug on my Windows 7 box, here it just works.
I will leave this issue open for a while in case anyone else reports it.
