### ISSUE TITLE
Watching Only Public Key Problem

### ISSUE THREAD

**Issue by herrschmidt** [stratisproject/electrum#5]
I installed Electrum Stratis 2.7.17 on an offline computer and copied the Master Public Key (Wallet - Master Public Keys). On my online computer in Electrum Stratis 2.7.17 I choose "Standard Wallet", then "Use public or private keys" and next I paste the Master Public Key. But the "Next" button is grayed out and I can't press it. My m pub key is definitely correct. Is this feature maybe not available in the Electrum Stratis client?

**Comment by dev0tion** [comment]
Hey @herrschmidt,
I was able to reproduce this issue. I will look in to it.
Thanks for reporting.

**Comment by herrschmidt** [comment]
Cool, thank you @dev0tion !

**Comment by dev0tion** [comment]
Hey @herrschmidt, 

I've fixed this in Pull Request #6, however I've found another bug when trying to sign a transaction with your offline wallet.
I will investigate this further after work on Breeze and a new version of Electrum will be released after I'm able to debug it.

**Comment by herrschmidt** [comment]
Great, thank you very much! Looking forward to Breeze and the Electrum fix :)
