### ISSUE TITLE
No balance

### ISSUE THREAD

**Issue by Daanleijser** [stratisproject/electrum#7]
Hey,

I have issue with my electrum stratis wallet. The wallet says i dont have any balance? How is this possible last week it was all there? He also says i dont have a history. I send 3 times tokens to my wallet!

Can someone help me?

Tnx in advance.

**Comment by dev0tion** [comment]
Hey @Daanleijser, 

Can you please click on the green/red circle in the bottom right of the application?
What's the value behind blocks?
What is your operation system?

**Comment by Daanleijser** [comment]
Pieter,

Bedoel je dit?
Blokketen 365271
Beginblokken worden opgehaald van 3 nodes
Server wasda.net
Mac.
Proxy none
Localhost 9050

**Comment by dev0tion** [comment]
Klopt, kan je anders even onze Slack joinen en mij een persoonlijk bericht sturen? Dan probeer ik je verder te helpen.
slackinvite.stratisplatform.com

**Comment by dev0tion** [comment]
Fixed through Slack, closing

**Comment by dev0tion** [comment]
Fixed through Slack, closing.
