### ISSUE TITLE
Won't Start on Linux Mint 17.3

### ISSUE THREAD

**Issue by Robert-Barclay** [stratisproject/electrum#9]
I have installed and re-installed but I keep getting the same issue. It won't start and I get no error message.

**Comment by dev0tion** [comment]
Can u start like this: sudo electrum-stratis -v, then it should give some more information.

**Comment by Robert-Barclay** [comment]
This is the error I get: 
Error: could not find paymentrequest_pb2.py. Create it with 'protoc --proto_path=lib/ --python_out=lib/ lib/paymentrequest.proto'

**Comment by dev0tion** [comment]
@Bearclay please complete all the steps to install the wallet, you can find them in the readme:
https://github.com/stratisproject/electrum-stratis/blob/master/README.rst
